# Generated by Django 2.1.7 on 2019-03-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190308_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='selectop',
            field=models.CharField(choices=[('tsto', 'tst1'), ('tste', 'tst2')], max_length=200, null=True),
        ),
    ]
