# Generated by Django 2.1.7 on 2019-03-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_selectop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='selectop',
            field=models.CharField(choices=[('tst1', 'tst1'), ('tst2', 'tst2')], default='tst2', max_length=200, null=True),
        ),
    ]
